services:
  salesappserver:
    # Use your Docker image name here
    image: goswamirohit/salesappserver:v1
    container_name: salesappserver
    restart: unless-stopped
    # Maps host port 4000 to the container's exposed port 8000 (from your Dockerfile)
    ports:
      - "55006:8000"
    # Tells Docker Compose to read environment variables from a .env file in the same directory
    env_file:
      - .env

    environment:
      - DATABASE_URL=${DATABASE_URL}
      #- DB_SCHEMA=${DB_SCHEMA}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_BUCKET_NAME=${SUPABASE_BUCKET_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - ADMIN_SERVICE_SECRET=${ADMIN_SERVICE_SECRET}

    networks:
      - brixta_appserver_net

networks:
  brixta_appserver_net:
    name: brixta_appserver_net